version: '3'

services:
  db:
    image: postgres:13
    ports:
      - "25432:5432"
    volumes:
      - $HOME/data/db2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chatshock
    container_name: chatshock_postgres
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "26379:6379"
    volumes:
      - $HOME/data/redis/chatshock.conf:/etc/redis/redis.conf
      - $HOME/data/redis/data:/data
    container_name: chatshock_redis
    restart: always
  minio:
    image: quay.io/minio/minio:RELEASE.2022-05-08T23-50-31Z
    command: server --address ":9000" --console-address ":9001" /data
    container_name: chatshock_minio
    ports:
      - "29090:9000"
      - "29091:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123456
    volumes:
      - $HOME/data/minio2/data:/data #映射当前目录下的data目录至容器内/data目录
      - $HOME/data/minio2/config:/root/.minio/ #映射配置目录
    privileged: true
    restart: always
