app:
  app_name: ChatShock
  app_host:
  app_port: 8088
  debug: true

db:
  db_name: chatshock
  db_user: postgres
  db_pass: 123456
  db_host: localhost
  db_port: 25432
  ssl_mode: disable

redis:
  redis_host: localhost
  redis_port: 26379

email:
  email_smtp: smtp.qq.com
  from_address:
  secret:
  from_name: "xiaozuhui"

minio:
  end_point: "localhost:29090"
  access_key_id: "quBdOrmVTXxS6UaH"
  secret_access_key: "6Dbdk1CLG9xM96IpB51A4xycFOIrhA9A"
  use_ssl: false
